from collections import Counter
from dataclasses import dataclass

import numpy as np
from transformers import AutoTokenizer, PreTrainedTokenizerBase


@dataclass
class RecitationScore:
    precision: float
    overlaps: int
    precision_per_n: dict[int, float]
    overlaps_per_n: dict[int, int]
    candidate_ngrams_per_n: dict[int, int]

    def __repr__(self) -> str:
        # with newlines for better readability
        return (
            f"RecitationScore(\n"
            f"    precision={self.precision:.4f},\n"
            f"    overlaps={self.overlaps},\n"
            f"    precision_per_n={self.precision_per_n},\n"
            f"    overlaps_per_n={self.overlaps_per_n},\n"
            f"    candidate_ngrams_per_n={self.candidate_ngrams_per_n}\n"
            f")"
        )


class RecitationScorer:
    """
    Computes a BLEU-style precision score to measure how much of a model's output
    overlaps with reference texts using high-order n-gram matching.

    Given:
        - candidate_text: the text generated by the model
        - reference_texts: a list of reference texts to compare agains
            for example: RAG documents used to generate the candidate text

    For each n in [n_min, n_max], compute:
        overlap_n = number of candidate n-grams found in reference texts
        total_n   = total number of candidate n-grams
        precision_n = overlap_n / total_n
        precision = (sum_n overlap_n) / (sum_n total_n)
    """

    def __init__(
        self,
        model_name: str = "openai-community/gpt2",
        n_min: int = 4,
        n_max: int = 8,
    ):
        """
        Args:
            model_name (str, optional): the name of the HuggingFace tokenizer to use.
            n_min (int, optional): Minimum n-gram size. Defaults to 4.
            n_max (int, optional): Maximum n-gram size. Defaults to 8.
        """
        self.tokenizer: PreTrainedTokenizerBase = AutoTokenizer.from_pretrained(
            model_name
        )
        self.n_min = n_min
        self.n_max = n_max

    def _get_ngrams(self, tokens: list[int], n: int) -> Counter[tuple[int, ...]]:
        return Counter(tuple(tokens[i : i + n]) for i in range(len(tokens) - n + 1))

    def _count_overlaps(
        self, cand_tokens: list[int], ref_tokens_list: list[list[int]]
    ) -> tuple[int, dict[int, int], dict[int, int]]:
        num_overlaps_per_n: dict[int, int] = {}
        num_candidate_ngrams_per_n: dict[int, int] = {}
        for n in range(self.n_min, self.n_max + 1):
            cand_ngrams = self._get_ngrams(cand_tokens, n)
            ref_ngrams = Counter()
            for ref in ref_tokens_list:
                ref_ngrams |= self._get_ngrams(ref, n)
            num_overlaps = sum((cand_ngrams & ref_ngrams).values())
            num_candidate_ngrams = sum(cand_ngrams.values())
            num_overlaps_per_n[n] = num_overlaps
            num_candidate_ngrams_per_n[n] = num_candidate_ngrams
        total_num_overlaps = int(np.sum(list(num_overlaps_per_n.values())))
        return total_num_overlaps, num_overlaps_per_n, num_candidate_ngrams_per_n

    def _calculate_precision(self, overlap: int, total: int) -> float:
        return overlap / total if total else 0.0

    def score(
        self,
        candidate_text: str,
        reference_texts: list[str],
        lowercase: bool = True,
    ) -> RecitationScore:
        if lowercase:
            candidate_text = candidate_text.lower()
            reference_texts = [r.lower() for r in reference_texts]
        cand_tokens = self.tokenizer.encode(candidate_text, add_special_tokens=False)
        ref_tokens = [
            self.tokenizer.encode(r, add_special_tokens=False) for r in reference_texts
        ]
        return self.score_tokenized(cand_tokens, ref_tokens)

    def score_tokenized(
        self, cand_tokens: list[int], ref_tokens_list: list[list[int]]
    ) -> RecitationScore:
        num_overlaps, num_overlaps_per_n, num_candidate_ngrams_per_n = (
            self._count_overlaps(cand_tokens, ref_tokens_list)
        )
        total_num_candidate_ngrams = sum(num_candidate_ngrams_per_n.values())
        precision = self._calculate_precision(num_overlaps, total_num_candidate_ngrams)
        precision_per_n = {
            n: self._calculate_precision(
                num_overlaps_per_n[n], num_candidate_ngrams_per_n[n]
            )
            for n in num_overlaps_per_n.keys()
        }
        return RecitationScore(
            precision=precision,
            overlaps=num_overlaps,
            precision_per_n=precision_per_n,
            overlaps_per_n=num_overlaps_per_n,
            candidate_ngrams_per_n=num_candidate_ngrams_per_n,
        )


if __name__ == "__main__":
    scorer = RecitationScorer(
        n_min=6,
        n_max=10,
    )
    candidate = "this is a test candidate text. This is a different reference text. 'this is a test candidate text' is what we want to match against. This is not a match."
    references = [
        "This is a reference text.",
        "Another reference text for testing.",
        "Yet another reference text.",
        "This is a different reference text. 'this is a test candidate text' is what we want to match against.",
    ]
    score = scorer.score(candidate, references)
    print(score)
