services:
  syft-pg-private:
    image: pgvector/pgvector:pg16
    shm_size: 2g
    container_name: syft-pg-private
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changethis
      POSTGRES_DB: syft-pg-private
    ports:
      - "5432:5432"
    volumes:
      - syft_pg_private_data:/var/lib/postgresql/data

  syft-pg-mock:
    image: pgvector/pgvector:pg16
    shm_size: 2g
    container_name: syft-pg-mock
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changethis
      POSTGRES_DB: syft-pg-mock
    ports:
      - "5433:5432"
    volumes:
      - syft_pg_mock_data:/var/lib/postgresql/data

volumes:
  syft_pg_private_data:
  syft_pg_mock_data:
